### ISSUE TITLE
Select all

### ISSUE THREAD

**Issue by BITMystery** [mwilliamson/python-graphjoiner#2]
Is there a way to select all books with the query like:
{
    books
}

Current example returns null without specifying columns.

**Comment by mwilliamson** [comment]
No, GraphQL requires that you explicitly specify which fields you want to retrieve.

**Comment by mwilliamson** [comment]
I've no idea what your use case is, but you can reflect on the types to get a list of the fields on each type.

**Comment by BITMystery** [comment]
Hi Michael,

Thank you for your answer. I have another question. How to support DateTime
type in graphjoiner?

Regards,
Chang

**Comment by mwilliamson** [comment]
It depends what you mean by supporting datetimes. In practice, all of our datetimes are serialised to strings when sent as JSON, so we leave the datetimes in the values that are generated by each fetching function. They're then converted into strings by our JSON serialiser.

**Comment by BITMystery** [comment]
Hi Michael,

Does graphjoiner support where condition for joined tables?

For example, for the SQL query

"SELECT title, name
FROM book JOIN author ON book.author_id=author.id
WHERE genre='comedy' AND author.id=2",

my GraphQL query would be:

"{
    books(genre: "comedy") {
        title
        author(id: 2) {
            name
        }
    }
}"

I've tried to achieve this but still cannot work out. Could you indicate
where should I make change in test_example_declarative.py?

Many thanks,
Chang

**Comment by mwilliamson** [comment]
After you've defined the `author` field, add an argument using the `arg` method on the field. For instance, if you're using SQLAlchemy:

```python
class Book(SqlAlchemyObjectType):
    ...
    author = single(...)
    @author.arg("id", Int)
    def author_arg_id(query, author_id):
        return query.filter(AuthorRecord.id == author_id)
```

In some cases, it's useful to hide the exact implementation of the filtering on the target type e.g. 

```python
class Book(SqlAlchemyObjectType):
    ...
    author = single(...)
    @author.arg("id", Int)
    def author_arg_id(query, author_id):
        return Author.filter_by_id(query, author_id)

class Author(SqlAlchemyObjectType):
    ...
    def filter_by_id(query, author_id):
        return query.filter(AuthorRecord.id == author_id)
```

**Comment by BITMystery** [comment]
Hi Michael,

Thank you for your answer.

That's what I exactly did, but the result turned out to be None. I've
checked carefully but cannot figure out where the problem is.

Chang

**Comment by BITMystery** [comment]
Please let me know if it works on your side.

**Comment by BITMystery** [comment]
Hi Michael,

I found where the problem is. When we filter author in Book, we should use
single_or_null instead of single, i.e.,

class Book(SqlAlchemyObjectType):
    ...
    author = single_or_null(...)
    @author.arg("id", Int)
    def author_arg_id(query, author_id):
        return query.filter(AuthorRecord.id == author_id)


The result is with the following form:

{
    "books": [
        {
            "title": "Leave It to Psmith",
            "author": {
                "id": 1,
                "name": "PG Wodehouse"
            }
        },
        {
            "title": "Right Ho, Jeeves",
            "author": {
                "id": 1,
                "name": "PG Wodehouse"
            }
        },
        {
            "title": "Catch-22",
            "author": null
        },
        {
            "title": "Around the World in Eighty Days",
            "author": null
        }
    ]
}

So we have to write another function to filter out those null items?

Chang

**Comment by mwilliamson** [comment]
Do you mean filter out books with null authors? If so, I think you're putting the argument in the wrong place. It needs to go on the `books` field on the root, since you're filtering books by author rather than filtering authors on books.

**Comment by BITMystery** [comment]
Hi Michael,

Understood. However, what if I want to select books whose author’s name equals to a variable author_name? I.e.

{
	books(author_name: “PG Wodehouse”) {
		title
		author {
			name
		}
	}
}

My code is as follows:

    class Root(RootType):
        books = many(lambda: select(Book))

        @books.arg("author_name", GraphQLString)
        def books_arg_author_name(query, author_name):
            return query.filter(BookRecord.author_id == AuthorRecord.id, AuthorRecord.name == author_name)

This method leads to very slow query when the table is large. It seems does repetitive table joins.

Am I coding right? Is there any better method?

Chang

**Comment by BITMystery** [comment]
The general question is to filter table A according to a column in the joined table B.

**Comment by mwilliamson** [comment]
I'm not sure exactly what SQL query that's going to generate -- I normally explicitly specify the joins using SQLAlchemy. For instance:

```python
@books.arg("authorName", String)
def books_arg_author_name(query, author_name):
    authors = aliased(AuthorRecord)
    return query \
        .join(authors, BookRecord.author_id == authors.id) \
        .filter(authors.name == author_name)
```

If that's still slow, then that sounds like a problem with either the way you're using SQLAlchemy or your database e.g. missing indices. I'd suggest finding out what the actual queries being generated are, and taking a look at their query plans.

**Comment by BITMystery** [comment]
By adding “echo=True” in create_engine() you can see the generated SQL queries.

I think your method is basically the same as mine in terms of efficiency. When selecting books, one join is used. When selecting author names, another join is used. If you have large table to test, you may find that this is much slower than putting the filter on authors (even though we need to further filter out null rows).

**Comment by mwilliamson** [comment]
My experience is that the queries generated in this style are efficient when run on PostgreSQL, provided that the indices are set up correctly. I can't really comment on your experience without seeing the queries that are being generated for you, and the resulting query plans.

**Comment by BITMystery** [comment]
I will do a test on PostgreSQL tomorrow (PS: here is night time in Australia :D). I will get back to you then. Thank you for your emails. Have a great day!

**Comment by BITMystery** [comment]
Hi Michael,

Just did some tests on a PostgreSQL database. Your solution took 0.47s on a
table join (between a 220K-row table and a 46K-row table) with where
conditions (resulted in 16K-row), which is as fast as my solution while is
only half time to the solution where I put filters on the wrong place.

So you are definitely right. Thank you.

Best,
Chang

**Comment by BITMystery** [comment]
One more finding. Consider two queries as follows:

query1 {
    authors {
        name
        books {
            title
        }
    }
}

query2 {
    books {
        title
        author {
            name
        }
    }
}

query1 and query2 are supposed to return the same rows in database, but
query1 is much slower than query2. Is that normal? Does the join order
matter in graphjoiner?

**Comment by mwilliamson** [comment]
I'd imagine they'd be similar speeds. I'd suggest you work out whether the time is spent in Python code or waiting for a response from the SQL server, and work from there.
